### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by ulvido** [PeterMitrano/CMake_for_Dummies_code#1]
I downloaded the project. 
make a build folder in sqrt.
go in build folder and write "cmake .."
*something happens new files and folders appeared.*
and then I write "make"
```
make: *** No targets specified and no makefile found.  Stop.
```

OS: Windows 10
CMAKE: v3.16.4

**Comment by PeterMitrano** [comment]
on windows CMake probably defaults to generating visual studio projects, you'll either need to specify GNU Makefiles as the generator, or just use visual studio

**Comment by thekhattamshud** [comment]
@PeterMitrano is absolutely right.
You'll have to use the following command once in the Build directory - 
cmake .. -G "Unix Makefiles"
Then follow along with the video and it all works as expected.
Note that you will need to have the required C/C++ compilers installed on your system - from mingw32 perhaps.
To view the cmake build generators, you can do cmake --help. You might then note that Visual Studio will be marked as default. The -G option allows you to override that operation by specifying the generator.
